name: Cópia dos arquivos STIX2 do MVT

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Checkout mvt-indicators repository
      uses: actions/checkout@v2
      with:
        repository: mvt-project/mvt-indicators
        path: mvt-indicators

    - name: Install dependencies
      run: |
        sudo apt-get install -y python3-pip
        pip3 install pyyaml

    - name: Parse indicators.yaml and download files
      run: |
        python3 <<'EOF'
        import yaml
        import os
        import subprocess

        with open('mvt-indicators/indicators.yaml', 'r') as file:
            indicators = yaml.safe_load(file)

        for indicator in indicators['indicators']:
            if 'github' in indicator:
                repo_info = indicator['github']
                owner = repo_info['owner']
                repo = repo_info['repo']
                branch = repo_info['branch']
                path = repo_info['path']
                raw_url = f'https://raw.githubusercontent.com/{owner}/{repo}/{branch}/{path}'
                dest_dir = os.path.join('mvt', owner)
                os.makedirs(dest_dir, exist_ok=True)
                dest_file = os.path.join(dest_dir, os.path.basename(path))
                subprocess.run(['curl', '-L', raw_url, '-o', dest_file])
        EOF

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add mvt/
        git commit -m 'Download STIX2 files from source repositories'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}